networks:
  ansh: {}
volumes:
  database:
services:
# docker run -d --name database --network ansh -v database:/var/lib/mysql database:1.0.0
  database:
    image: database:1.0.0
    networks:
    - ansh
    volumes:
    - database:/var/lib/database
    container_name: database
  
#docker run -d --name backend --network ansh backend:1.0.0 sleep 5
  backend:
    image: backend:1.0.0
    networks:
    - ansh
    container_name: backend
    command: sh -c "sleep 10 && node /opt/backend/index.js"
    depends_on:
    - database

# docker run -d --name frontend --network ansh  database:1.0.0 -p 80:80
  frontend:
    image: frontend:1.0.0
    networks:
    - ansh
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
